# -*- coding: utf-8 -*-
"""Parse Promela output generated by ltl2ba."""

import re


class ParseException(Exception):
    """Report an error while parsing Promela text."""


class Parser:
    """Parse an ltl2ba Promela never claim."""

    # Expression used to consume whitespace.
    white_regex = re.compile(r"\s+")

    # Expressions describing the input language.
    vertex_regex = re.compile(r"(?P<name>\w+_\w+):\s*")
    never_regex = re.compile(
        r"never\s*\{\s*/\*(?P<formula>.*?)\*/",
        re.DOTALL,
    )
    if_regex = re.compile(r"if")
    edge_regex = re.compile(
        r":: (?P<cond>\(.*\)) -> goto (?P<dest>\w+_\w+)"
    )
    fi_regex = re.compile(r"fi;")
    skip_regex = re.compile(r"skip")
    false_regex = re.compile(r"false;")
    end_regex = re.compile(r"\}")

    def __init__(self, instring):
        """Initialize the parser with Promela input text."""
        self.instring = instring
        self.pos = 0
        self.formula = None
        self.states = set()

    def eat_whitespace(self):
        """Consume whitespace from the current parser position."""
        match = self.white_regex.match(self.instring, self.pos)

        while match is not None:
            self.pos += len(match.group(0))
            match = self.white_regex.match(self.instring, self.pos)

    def accept(self, expression, strip_whitespace=True):
        """Accept an expression at the current parser position."""
        if strip_whitespace:
            self.eat_whitespace()

        match = expression.match(self.instring, self.pos)

        if match is None:
            return None

        self.pos += len(match.group(0))
        return match.groupdict()

    def parse(self):
        """Parse the input and return the Büchi transition dictionary."""
        edges = {}

        never_claim = self.accept(self.never_regex)
        if never_claim is None:
            raise ParseException("Expected a never claim header.")
        self.formula = never_claim["formula"]

        vertex = self.accept(self.vertex_regex)

        while vertex is not None:
            vertex_name = vertex["name"]
            if vertex_name in self.states:
                raise ParseException(
                    f"Duplicate state declaration: {vertex_name}"
                )
            self.states.add(vertex_name)

            if self.accept(self.if_regex) is not None:
                edge = self.accept(self.edge_regex)
                edge_count = 0

                while edge is not None:
                    edges[(vertex_name, edge["dest"])] = edge["cond"]
                    edge_count += 1
                    edge = self.accept(self.edge_regex)

                if edge_count == 0:
                    raise ParseException(
                        f"State {vertex_name} has an empty if block."
                    )
                if self.accept(self.fi_regex) is None:
                    raise ParseException(
                        f"State {vertex_name} is missing 'fi;'."
                    )

            elif self.accept(self.skip_regex) is not None:
                # A skip statement represents a self-loop.
                edges[(vertex_name, vertex_name)] = "1"

            elif self.accept(self.false_regex) is not None:
                # A false statement declares an isolated blocking state.
                pass

            else:
                remainder = self.instring[self.pos:]
                raise ParseException(
                    "Expected 'if', 'skip', or 'false', "
                    f"but got: {remainder}"
                )

            vertex = self.accept(self.vertex_regex)

        if self.accept(self.end_regex) is None:
            raise ParseException("Expected closing '}'.")
        self.eat_whitespace()

        if self.pos != len(self.instring):
            remainder = self.instring[self.pos:]
            raise ParseException(
                f"Input not fully parsed. Remainder: {remainder}"
            )

        if not self.states:
            raise ParseException("The never claim declares no states.")

        undeclared_targets = {
            target
            for _, target in edges
            if target not in self.states
        }
        if undeclared_targets:
            raise ParseException(
                "Edges target undeclared states: "
                + ", ".join(sorted(undeclared_targets))
            )

        return edges


def parse(promela):
    """Parse Promela text and return its transition dictionary."""
    parser = Parser(promela)
    return parser.parse()


def find_states(edges, declared_states=()):
    """Return all, initial, and accepting Büchi states."""
    states = set(declared_states)
    initial_states = set()
    accepting_states = set()

    for source, target in edges:
        states.add(source)
        states.add(target)

    for state in states:
        if state.startswith("accept"):
            accepting_states.add(state)

        if state.endswith("init"):
            initial_states.add(state)

    return (
        list(states),
        list(initial_states),
        list(accepting_states),
    )


def find_symbols(formula):
    """Return the sorted atomic propositions found in a formula."""
    symbol_regex = re.compile(r"[a-z]+[a-z0-9_]*")
    symbols = set(symbol_regex.findall(formula)) - {"true", "false"}

    return sorted(symbols)
