"""Integration tests using the real ltl2ba executable."""

import shutil

import pytest

from ltl_automaton_planner_core.ltl_tools.ltl2ba import (
    parse_ltl,
    run_ltl2ba,
)
from ltl_automaton_planner_core.ltl_tools.promela import (
    find_states,
)


LTL2BA_PATH = shutil.which("ltl2ba")

pytestmark = pytest.mark.skipif(
    LTL2BA_PATH is None,
    reason="The real ltl2ba executable is not available in PATH.",
)


def test_real_ltl2ba_translation() -> None:
    """Translate an LTL formula using the real executable."""
    output = run_ltl2ba("<> cargo")

    assert "never {" in output
    assert "cargo" in output


def test_real_ltl2ba_output_parsing() -> None:
    """Parse transitions generated by the real executable."""
    edges = parse_ltl("<> cargo")

    assert edges
    assert any("cargo" in guard for guard in edges.values())

    states, initial_states, accepting_states = find_states(edges)

    assert states
    assert initial_states
    assert accepting_states
