<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ltl_automaton_core</name>
  <version>0.1.0</version>
  <description>ROS 2 aggregate package for the LTL automaton core stack.</description>
  <maintainer email="1209634202@qq.com">yuhling</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ltl_automaton_msgs</exec_depend>
  <exec_depend>ltl_automaton_planner_core</exec_depend>
  <exec_depend>ltl_automaton_planner</exec_depend>
  <exec_depend>ltl_automaton_execution</exec_depend>
  <exec_depend>ltl_automaton_std_transition_systems</exec_depend>
  <exec_depend>ltl_automaton_hil_mic</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
